export const FREELANCER_GET_REQUEST='TRAINING_FETCH_REQUEST'
export const FREELANCER_GET_SUCCESS='TRAINING_FETCH_SUCCESS'
export const FREELANCER_GET_FAIL='TRAINING_FETCH_FAIL'

export const FREELANCER_GET_RESET='NOTE_FETCH_RESET'

