export const TRAINING_FETCH_REQUEST='TRAINING_FETCH_REQUEST'
export const TRAINING_FETCH_SUCCESS='TRAINING_FETCH_SUCCESS'
export const TRAINING_FETCH_FAIL='TRAINING_FETCH_FAIL'

export const NOTE_FETCH_RESET='NOTE_FETCH_RESET'

export const TRAINING_ADD_REQUEST='TRAINING_ADD_REQUEST'
export const TRAINING_ADD_SUCCESS='TRAINING_ADD_SUCCESS'
export const TRAINING_ADD_FAIL='TRAINING_ADD_FAIL'
export const TRAINING_ADD_RESET='NOTE_ADD_RESET'